### ISSUE TITLE
Error Handling bad topics

### ISSUE THREAD

**Issue by butlermatt** [pulyaevskiy/dart-kafka#3]
I'm not entirely sure where, but there appears to be an issue when I'm trying to consume a topic which may not exist. The issue is that an error is being thrown but never caught even when I wrap the consume in a try/catch block on my end.

Here's a sample code:

```
try {
      var consumer = new Consumer(_session, _cGroup, topics, 360, 1);
      await for (MessageEnvelope env in consumer.consume()) {
        var value = new String.fromCharCodes(env.message.value);
        print('Received value: $value');
        env.ack();
        yield value;
      }
    } catch (e) {
      logger.warning('Error subscribing', e);
    }
```

But even with that as the only place that consume is being called, it's still crashing my app with this:

```
Unhandled exception:
Bad state: No topic tesTopic found in metadata.
#0      MetadataResponse.getTopicMetadata.<anonymous closure> (package:kafka/src/protocol/metadata_api.dart:76:13)
#1      Object&ListMixin.firstWhere (dart:collection/list.dart:132)
#2      MetadataResponse.getTopicMetadata (package:kafka/src/protocol/metadata_api.dart:74:19)
#3      Consumer._buildWorkers.<_buildWorkers_async_body>.<anonymous closure>.<anonymous closure> (package:kafka/src/consumer.dart:93:27)
#4      List.forEach (dart:core-patch/growable_array.dart:233)
#5      Consumer._buildWorkers.<_buildWorkers_async_body>.<anonymous closure> (package:kafka/src/consumer.dart:92:18)
#6      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#7      Consumer._buildWorkers.<_buildWorkers_async_body> (package:kafka/src/consumer.dart:91:21)
#8      _RootZone.runUnary (dart:async/zone.dart:1149)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#11     _Future._complete (dart:async/future_impl.dart:366)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#13     KafkaSession.getMetadata.<getMetadata_async_body> (package:kafka/src/session.dart)
#14     _RootZone.runUnary (dart:async/zone.dart:1149)
#15     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#16     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#17     _Future._completeWithValue (dart:async/future_impl.dart:376)
#18     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#20     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

Process finished with exit code 255
```

**Comment by pulyaevskiy** [comment]
Thanks again for your feedback! I think I've found the source of this error and will submit a PR shortly.

Will keep you posted.

**Comment by pulyaevskiy** [comment]
Closing this and moving discussion to #4 .
